### ISSUE TITLE
Sign Invoice

### ISSUE THREAD

**Issue by CodeliaNet** [mrkindy/ETAHttpSignature#3]
Hey,

Thanks about this tool, But while I using it, I have the below error

10/26/2022 10:30:59 PM|Error|WebSocket.messages|Net.Pkcs11Interop.Common.UnmanagedException: Unable to load library. Error code: 0x0000007E. Error detail: The specified module could not be found.
                                at Net.Pkcs11Interop.Common.UnmanagedLibrary.Load(String fileName)
                                at Net.Pkcs11Interop.LowLevelAPI41.Pkcs11Library..ctor(String libraryPath)
                                at Net.Pkcs11Interop.HighLevelAPI41.Pkcs11Library..ctor(Pkcs11InteropFactories factories, String libraryPath, AppType appType)
                                at Net.Pkcs11Interop.HighLevelAPI41.Factories.Pkcs11LibraryFactory.LoadPkcs11Library(Pkcs11InteropFactories factories, String libraryPath, AppType appType)
                                at Net.Pkcs11Interop.HighLevelAPI.Factories.Pkcs11LibraryFactory.LoadPkcs11Library(Pkcs11InteropFactories factories, String libraryPath, AppType appType)
                                at HttpSignature.Signature.SignWithCMS(String serializedJson) in C:\Users\admin\source\repos\HttpSignature\HttpSignature\Signature.cs:line 55
                                at HttpSignature.Signature.OnMessage(MessageEventArgs e) in C:\Users\admin\source\repos\HttpSignature\HttpSignature\Signature.cs:line 38
                                at WebSocketSharp.Server.WebSocketBehavior.onMessage(Object sender, MessageEventArgs e)
                                at WebSocketSharp.Ext.Emit[TEventArgs](EventHandler`1 eventHandler, Object sender, TEventArgs e)
                                at WebSocketSharp.WebSocket.messages(MessageEventArgs e)

**Comment by amrelghamrawy** [comment]
Hi ,
Thanks for your effort ,
I had Extracted ETAHttpSignature.zip files and Run Http Signature.exe but it doesn't do any thing
is there is a custom configration or settings that i must make before installation
hint ..... I'm not a c# developer

**Comment by devhus** [comment]
The "Unable to load library" error occurred due to the lack of the required DLLs files on your device.
Please download and install ePass 2013 driver so you can fix this issue.
https://egypttrust.com/%d8%aa%d8%b9%d8%b1%d9%8a%d9%81-%d8%a7%d9%84%d8%aa%d9%88%d9%82%d9%8a%d8%b9-%d8%a7%d9%84%d8%ae%d8%aa%d9%85-%d8%a7%d9%84%d8%a5%d9%84%d9%83%d8%aa%d8%b1%d9%88%d9%86%d9%8a-%d9%88%d9%8a%d9%86%d8%af%d9%88/
